//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProxyVyV.cl.facturacion.ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsplanoSoap", Namespace="http://tempuri.org")]
    public partial class wsplano : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcesarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBoletaTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXMLDteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback AnularGuiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsplano() {
            this.Url = global::ProxyVyV.Properties.Settings.Default.ProxyVyV_cl_facturacion_ws_wsplano;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcesarCompletedEventHandler ProcesarCompleted;
        
        /// <remarks/>
        public event ObtenerLinkCompletedEventHandler ObtenerLinkCompleted;
        
        /// <remarks/>
        public event getBoletaTicketCompletedEventHandler getBoletaTicketCompleted;
        
        /// <remarks/>
        public event getXMLDteCompletedEventHandler getXMLDteCompleted;
        
        /// <remarks/>
        public event AltNumCompletedEventHandler AltNumCompleted;
        
        /// <remarks/>
        public event RegIPCompletedEventHandler RegIPCompleted;
        
        /// <remarks/>
        public event getIPCompletedEventHandler getIPCompleted;
        
        /// <remarks/>
        public event EliminarDocCompletedEventHandler EliminarDocCompleted;
        
        /// <remarks/>
        public event AnularGuiaCompletedEventHandler AnularGuiaCompleted;
        
        /// <remarks/>
        public event OnlineCompletedEventHandler OnlineCompleted;
        
        /// <remarks/>
        public event VersionCompletedEventHandler VersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Procesar", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Procesar(logininfo login, string file, int formato) {
            object[] results = this.Invoke("Procesar", new object[] {
                        login,
                        file,
                        formato});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesarAsync(logininfo login, string file, int formato) {
            this.ProcesarAsync(login, file, formato, null);
        }
        
        /// <remarks/>
        public void ProcesarAsync(logininfo login, string file, int formato, object userState) {
            if ((this.ProcesarOperationCompleted == null)) {
                this.ProcesarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarOperationCompleted);
            }
            this.InvokeAsync("Procesar", new object[] {
                        login,
                        file,
                        formato}, this.ProcesarOperationCompleted, userState);
        }
        
        private void OnProcesarOperationCompleted(object arg) {
            if ((this.ProcesarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarCompleted(this, new ProcesarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerLink", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerLink(logininfo login, string tpomov, string folio, string tipo, string cedible) {
            object[] results = this.Invoke("ObtenerLink", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo,
                        cedible});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerLinkAsync(logininfo login, string tpomov, string folio, string tipo, string cedible) {
            this.ObtenerLinkAsync(login, tpomov, folio, tipo, cedible, null);
        }
        
        /// <remarks/>
        public void ObtenerLinkAsync(logininfo login, string tpomov, string folio, string tipo, string cedible, object userState) {
            if ((this.ObtenerLinkOperationCompleted == null)) {
                this.ObtenerLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerLinkOperationCompleted);
            }
            this.InvokeAsync("ObtenerLink", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo,
                        cedible}, this.ObtenerLinkOperationCompleted, userState);
        }
        
        private void OnObtenerLinkOperationCompleted(object arg) {
            if ((this.ObtenerLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerLinkCompleted(this, new ObtenerLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBoletaTicket", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBoletaTicket(logininfo login, string ticket) {
            object[] results = this.Invoke("getBoletaTicket", new object[] {
                        login,
                        ticket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBoletaTicketAsync(logininfo login, string ticket) {
            this.getBoletaTicketAsync(login, ticket, null);
        }
        
        /// <remarks/>
        public void getBoletaTicketAsync(logininfo login, string ticket, object userState) {
            if ((this.getBoletaTicketOperationCompleted == null)) {
                this.getBoletaTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBoletaTicketOperationCompleted);
            }
            this.InvokeAsync("getBoletaTicket", new object[] {
                        login,
                        ticket}, this.getBoletaTicketOperationCompleted, userState);
        }
        
        private void OngetBoletaTicketOperationCompleted(object arg) {
            if ((this.getBoletaTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBoletaTicketCompleted(this, new getBoletaTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getXMLDte", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getXMLDte(logininfo login, string tpomov, string folio, string tipo) {
            object[] results = this.Invoke("getXMLDte", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getXMLDteAsync(logininfo login, string tpomov, string folio, string tipo) {
            this.getXMLDteAsync(login, tpomov, folio, tipo, null);
        }
        
        /// <remarks/>
        public void getXMLDteAsync(logininfo login, string tpomov, string folio, string tipo, object userState) {
            if ((this.getXMLDteOperationCompleted == null)) {
                this.getXMLDteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXMLDteOperationCompleted);
            }
            this.InvokeAsync("getXMLDte", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo}, this.getXMLDteOperationCompleted, userState);
        }
        
        private void OngetXMLDteOperationCompleted(object arg) {
            if ((this.getXMLDteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXMLDteCompleted(this, new getXMLDteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltNum", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AltNum(logininfo login, string folio, string tipo, string campo) {
            object[] results = this.Invoke("AltNum", new object[] {
                        login,
                        folio,
                        tipo,
                        campo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AltNumAsync(logininfo login, string folio, string tipo, string campo) {
            this.AltNumAsync(login, folio, tipo, campo, null);
        }
        
        /// <remarks/>
        public void AltNumAsync(logininfo login, string folio, string tipo, string campo, object userState) {
            if ((this.AltNumOperationCompleted == null)) {
                this.AltNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltNumOperationCompleted);
            }
            this.InvokeAsync("AltNum", new object[] {
                        login,
                        folio,
                        tipo,
                        campo}, this.AltNumOperationCompleted, userState);
        }
        
        private void OnAltNumOperationCompleted(object arg) {
            if ((this.AltNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltNumCompleted(this, new AltNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegIP", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegIP(logininfo login, string puerto) {
            object[] results = this.Invoke("RegIP", new object[] {
                        login,
                        puerto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegIPAsync(logininfo login, string puerto) {
            this.RegIPAsync(login, puerto, null);
        }
        
        /// <remarks/>
        public void RegIPAsync(logininfo login, string puerto, object userState) {
            if ((this.RegIPOperationCompleted == null)) {
                this.RegIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegIPOperationCompleted);
            }
            this.InvokeAsync("RegIP", new object[] {
                        login,
                        puerto}, this.RegIPOperationCompleted, userState);
        }
        
        private void OnRegIPOperationCompleted(object arg) {
            if ((this.RegIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegIPCompleted(this, new RegIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getIP", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getIP() {
            object[] results = this.Invoke("getIP", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getIPAsync() {
            this.getIPAsync(null);
        }
        
        /// <remarks/>
        public void getIPAsync(object userState) {
            if ((this.getIPOperationCompleted == null)) {
                this.getIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIPOperationCompleted);
            }
            this.InvokeAsync("getIP", new object[0], this.getIPOperationCompleted, userState);
        }
        
        private void OngetIPOperationCompleted(object arg) {
            if ((this.getIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIPCompleted(this, new getIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarDoc", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminarDoc(logininfo login, string tpomov, string folio, string tipo) {
            object[] results = this.Invoke("EliminarDoc", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarDocAsync(logininfo login, string tpomov, string folio, string tipo) {
            this.EliminarDocAsync(login, tpomov, folio, tipo, null);
        }
        
        /// <remarks/>
        public void EliminarDocAsync(logininfo login, string tpomov, string folio, string tipo, object userState) {
            if ((this.EliminarDocOperationCompleted == null)) {
                this.EliminarDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDocOperationCompleted);
            }
            this.InvokeAsync("EliminarDoc", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo}, this.EliminarDocOperationCompleted, userState);
        }
        
        private void OnEliminarDocOperationCompleted(object arg) {
            if ((this.EliminarDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDocCompleted(this, new EliminarDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AnularGuia", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AnularGuia(logininfo login, string tpomov, string folio, string tipo) {
            object[] results = this.Invoke("AnularGuia", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AnularGuiaAsync(logininfo login, string tpomov, string folio, string tipo) {
            this.AnularGuiaAsync(login, tpomov, folio, tipo, null);
        }
        
        /// <remarks/>
        public void AnularGuiaAsync(logininfo login, string tpomov, string folio, string tipo, object userState) {
            if ((this.AnularGuiaOperationCompleted == null)) {
                this.AnularGuiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnularGuiaOperationCompleted);
            }
            this.InvokeAsync("AnularGuia", new object[] {
                        login,
                        tpomov,
                        folio,
                        tipo}, this.AnularGuiaOperationCompleted, userState);
        }
        
        private void OnAnularGuiaOperationCompleted(object arg) {
            if ((this.AnularGuiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnularGuiaCompleted(this, new AnularGuiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Online", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Online() {
            object[] results = this.Invoke("Online", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OnlineAsync() {
            this.OnlineAsync(null);
        }
        
        /// <remarks/>
        public void OnlineAsync(object userState) {
            if ((this.OnlineOperationCompleted == null)) {
                this.OnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineOperationCompleted);
            }
            this.InvokeAsync("Online", new object[0], this.OnlineOperationCompleted, userState);
        }
        
        private void OnOnlineOperationCompleted(object arg) {
            if ((this.OnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnlineCompleted(this, new OnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Version() {
            object[] results = this.Invoke("Version", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAsync() {
            this.VersionAsync(null);
        }
        
        /// <remarks/>
        public void VersionAsync(object userState) {
            if ((this.VersionOperationCompleted == null)) {
                this.VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionOperationCompleted);
            }
            this.InvokeAsync("Version", new object[0], this.VersionOperationCompleted, userState);
        }
        
        private void OnVersionOperationCompleted(object arg) {
            if ((this.VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionCompleted(this, new VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class logininfo {
        
        private string usuarioField;
        
        private string rutField;
        
        private string claveField;
        
        private string puertoField;
        
        private string incluyeLinkField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string Puerto {
            get {
                return this.puertoField;
            }
            set {
                this.puertoField = value;
            }
        }
        
        /// <remarks/>
        public string IncluyeLink {
            get {
                return this.incluyeLinkField;
            }
            set {
                this.incluyeLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ProcesarCompletedEventHandler(object sender, ProcesarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObtenerLinkCompletedEventHandler(object sender, ObtenerLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBoletaTicketCompletedEventHandler(object sender, getBoletaTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBoletaTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBoletaTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getXMLDteCompletedEventHandler(object sender, getXMLDteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXMLDteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXMLDteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AltNumCompletedEventHandler(object sender, AltNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegIPCompletedEventHandler(object sender, RegIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getIPCompletedEventHandler(object sender, getIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarDocCompletedEventHandler(object sender, EliminarDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AnularGuiaCompletedEventHandler(object sender, AnularGuiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnularGuiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnularGuiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OnlineCompletedEventHandler(object sender, OnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VersionCompletedEventHandler(object sender, VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591