//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProxyVyV.DteLocalVyV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DTELocalSoap", Namespace="http://tempuri.org/")]
    public partial class DTELocal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Carga_TXTDTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback Carga_TXTBoletaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Solicitar_FolioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Carga_LibroCVOperationCompleted;
        
        private System.Threading.SendOrPostCallback Carga_LibroGuiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Estado_DTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback Confirmar_DoctoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DTELocal() {
            this.Url = global::ProxyVyV.Properties.Settings.Default.ProxyVyV_DteLocalVyV_DTELocal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Carga_TXTDTECompletedEventHandler Carga_TXTDTECompleted;
        
        /// <remarks/>
        public event Carga_TXTBoletaCompletedEventHandler Carga_TXTBoletaCompleted;
        
        /// <remarks/>
        public event Solicitar_FolioCompletedEventHandler Solicitar_FolioCompleted;
        
        /// <remarks/>
        public event Carga_LibroCVCompletedEventHandler Carga_LibroCVCompleted;
        
        /// <remarks/>
        public event Carga_LibroGuiaCompletedEventHandler Carga_LibroGuiaCompleted;
        
        /// <remarks/>
        public event Estado_DTECompletedEventHandler Estado_DTECompleted;
        
        /// <remarks/>
        public event Confirmar_DoctoCompletedEventHandler Confirmar_DoctoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Carga_TXTDTE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcesarTXT Carga_TXTDTE(string ArchivoTXT, string TipoArchivo) {
            object[] results = this.Invoke("Carga_TXTDTE", new object[] {
                        ArchivoTXT,
                        TipoArchivo});
            return ((ProcesarTXT)(results[0]));
        }
        
        /// <remarks/>
        public void Carga_TXTDTEAsync(string ArchivoTXT, string TipoArchivo) {
            this.Carga_TXTDTEAsync(ArchivoTXT, TipoArchivo, null);
        }
        
        /// <remarks/>
        public void Carga_TXTDTEAsync(string ArchivoTXT, string TipoArchivo, object userState) {
            if ((this.Carga_TXTDTEOperationCompleted == null)) {
                this.Carga_TXTDTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarga_TXTDTEOperationCompleted);
            }
            this.InvokeAsync("Carga_TXTDTE", new object[] {
                        ArchivoTXT,
                        TipoArchivo}, this.Carga_TXTDTEOperationCompleted, userState);
        }
        
        private void OnCarga_TXTDTEOperationCompleted(object arg) {
            if ((this.Carga_TXTDTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Carga_TXTDTECompleted(this, new Carga_TXTDTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Carga_TXTBoleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcesarTXTBoleta Carga_TXTBoleta(string ArchivoTXT, string TipoArchivo) {
            object[] results = this.Invoke("Carga_TXTBoleta", new object[] {
                        ArchivoTXT,
                        TipoArchivo});
            return ((ProcesarTXTBoleta)(results[0]));
        }
        
        /// <remarks/>
        public void Carga_TXTBoletaAsync(string ArchivoTXT, string TipoArchivo) {
            this.Carga_TXTBoletaAsync(ArchivoTXT, TipoArchivo, null);
        }
        
        /// <remarks/>
        public void Carga_TXTBoletaAsync(string ArchivoTXT, string TipoArchivo, object userState) {
            if ((this.Carga_TXTBoletaOperationCompleted == null)) {
                this.Carga_TXTBoletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarga_TXTBoletaOperationCompleted);
            }
            this.InvokeAsync("Carga_TXTBoleta", new object[] {
                        ArchivoTXT,
                        TipoArchivo}, this.Carga_TXTBoletaOperationCompleted, userState);
        }
        
        private void OnCarga_TXTBoletaOperationCompleted(object arg) {
            if ((this.Carga_TXTBoletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Carga_TXTBoletaCompleted(this, new Carga_TXTBoletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Solicitar_Folio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SolicitarFolio Solicitar_Folio(string RutEmpresa, int TipoDocto) {
            object[] results = this.Invoke("Solicitar_Folio", new object[] {
                        RutEmpresa,
                        TipoDocto});
            return ((SolicitarFolio)(results[0]));
        }
        
        /// <remarks/>
        public void Solicitar_FolioAsync(string RutEmpresa, int TipoDocto) {
            this.Solicitar_FolioAsync(RutEmpresa, TipoDocto, null);
        }
        
        /// <remarks/>
        public void Solicitar_FolioAsync(string RutEmpresa, int TipoDocto, object userState) {
            if ((this.Solicitar_FolioOperationCompleted == null)) {
                this.Solicitar_FolioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitar_FolioOperationCompleted);
            }
            this.InvokeAsync("Solicitar_Folio", new object[] {
                        RutEmpresa,
                        TipoDocto}, this.Solicitar_FolioOperationCompleted, userState);
        }
        
        private void OnSolicitar_FolioOperationCompleted(object arg) {
            if ((this.Solicitar_FolioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Solicitar_FolioCompleted(this, new Solicitar_FolioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Carga_LibroCV", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcesarLCV Carga_LibroCV(string ArchivoTXT, string TipoArchivo) {
            object[] results = this.Invoke("Carga_LibroCV", new object[] {
                        ArchivoTXT,
                        TipoArchivo});
            return ((ProcesarLCV)(results[0]));
        }
        
        /// <remarks/>
        public void Carga_LibroCVAsync(string ArchivoTXT, string TipoArchivo) {
            this.Carga_LibroCVAsync(ArchivoTXT, TipoArchivo, null);
        }
        
        /// <remarks/>
        public void Carga_LibroCVAsync(string ArchivoTXT, string TipoArchivo, object userState) {
            if ((this.Carga_LibroCVOperationCompleted == null)) {
                this.Carga_LibroCVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarga_LibroCVOperationCompleted);
            }
            this.InvokeAsync("Carga_LibroCV", new object[] {
                        ArchivoTXT,
                        TipoArchivo}, this.Carga_LibroCVOperationCompleted, userState);
        }
        
        private void OnCarga_LibroCVOperationCompleted(object arg) {
            if ((this.Carga_LibroCVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Carga_LibroCVCompleted(this, new Carga_LibroCVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Carga_LibroGuia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProcesarLGuia Carga_LibroGuia(string ArchivoTXT, string TipoArchivo) {
            object[] results = this.Invoke("Carga_LibroGuia", new object[] {
                        ArchivoTXT,
                        TipoArchivo});
            return ((ProcesarLGuia)(results[0]));
        }
        
        /// <remarks/>
        public void Carga_LibroGuiaAsync(string ArchivoTXT, string TipoArchivo) {
            this.Carga_LibroGuiaAsync(ArchivoTXT, TipoArchivo, null);
        }
        
        /// <remarks/>
        public void Carga_LibroGuiaAsync(string ArchivoTXT, string TipoArchivo, object userState) {
            if ((this.Carga_LibroGuiaOperationCompleted == null)) {
                this.Carga_LibroGuiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarga_LibroGuiaOperationCompleted);
            }
            this.InvokeAsync("Carga_LibroGuia", new object[] {
                        ArchivoTXT,
                        TipoArchivo}, this.Carga_LibroGuiaOperationCompleted, userState);
        }
        
        private void OnCarga_LibroGuiaOperationCompleted(object arg) {
            if ((this.Carga_LibroGuiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Carga_LibroGuiaCompleted(this, new Carga_LibroGuiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Estado_DTE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstadoDocto Estado_DTE(string RUTEmpresa, int TipoDocto, double NroDocto) {
            object[] results = this.Invoke("Estado_DTE", new object[] {
                        RUTEmpresa,
                        TipoDocto,
                        NroDocto});
            return ((EstadoDocto)(results[0]));
        }
        
        /// <remarks/>
        public void Estado_DTEAsync(string RUTEmpresa, int TipoDocto, double NroDocto) {
            this.Estado_DTEAsync(RUTEmpresa, TipoDocto, NroDocto, null);
        }
        
        /// <remarks/>
        public void Estado_DTEAsync(string RUTEmpresa, int TipoDocto, double NroDocto, object userState) {
            if ((this.Estado_DTEOperationCompleted == null)) {
                this.Estado_DTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstado_DTEOperationCompleted);
            }
            this.InvokeAsync("Estado_DTE", new object[] {
                        RUTEmpresa,
                        TipoDocto,
                        NroDocto}, this.Estado_DTEOperationCompleted, userState);
        }
        
        private void OnEstado_DTEOperationCompleted(object arg) {
            if ((this.Estado_DTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Estado_DTECompleted(this, new Estado_DTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Confirmar_Docto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstadoDocto Confirmar_Docto(string RutEmpresa, string TipoDocto, double NroDocto) {
            object[] results = this.Invoke("Confirmar_Docto", new object[] {
                        RutEmpresa,
                        TipoDocto,
                        NroDocto});
            return ((EstadoDocto)(results[0]));
        }
        
        /// <remarks/>
        public void Confirmar_DoctoAsync(string RutEmpresa, string TipoDocto, double NroDocto) {
            this.Confirmar_DoctoAsync(RutEmpresa, TipoDocto, NroDocto, null);
        }
        
        /// <remarks/>
        public void Confirmar_DoctoAsync(string RutEmpresa, string TipoDocto, double NroDocto, object userState) {
            if ((this.Confirmar_DoctoOperationCompleted == null)) {
                this.Confirmar_DoctoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmar_DoctoOperationCompleted);
            }
            this.InvokeAsync("Confirmar_Docto", new object[] {
                        RutEmpresa,
                        TipoDocto,
                        NroDocto}, this.Confirmar_DoctoOperationCompleted, userState);
        }
        
        private void OnConfirmar_DoctoOperationCompleted(object arg) {
            if ((this.Confirmar_DoctoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Confirmar_DoctoCompleted(this, new Confirmar_DoctoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcesarTXT {
        
        private byte[] pDFField;
        
        private byte[] pDFCedibleField;
        
        private string xMLField;
        
        private int estatusField;
        
        private string msgEstatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDFCedible {
            get {
                return this.pDFCedibleField;
            }
            set {
                this.pDFCedibleField = value;
            }
        }
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string MsgEstatus {
            get {
                return this.msgEstatusField;
            }
            set {
                this.msgEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoDocto {
        
        private int estadoDTEField;
        
        private string descEstadoField;
        
        private int estatusField;
        
        private string msgEstatusField;
        
        /// <remarks/>
        public int EstadoDTE {
            get {
                return this.estadoDTEField;
            }
            set {
                this.estadoDTEField = value;
            }
        }
        
        /// <remarks/>
        public string DescEstado {
            get {
                return this.descEstadoField;
            }
            set {
                this.descEstadoField = value;
            }
        }
        
        /// <remarks/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string MsgEstatus {
            get {
                return this.msgEstatusField;
            }
            set {
                this.msgEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcesarLGuia {
        
        private int estatusField;
        
        private string msgEstatusField;
        
        /// <remarks/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string MsgEstatus {
            get {
                return this.msgEstatusField;
            }
            set {
                this.msgEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcesarLCV {
        
        private int estatusField;
        
        private string msgEstatusField;
        
        /// <remarks/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string MsgEstatus {
            get {
                return this.msgEstatusField;
            }
            set {
                this.msgEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitarFolio {
        
        private int tipoDoctoField;
        
        private int folioField;
        
        private int estatusField;
        
        private string msgEstatusField;
        
        /// <remarks/>
        public int TipoDocto {
            get {
                return this.tipoDoctoField;
            }
            set {
                this.tipoDoctoField = value;
            }
        }
        
        /// <remarks/>
        public int Folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string MsgEstatus {
            get {
                return this.msgEstatusField;
            }
            set {
                this.msgEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcesarTXTBoleta {
        
        private byte[] pDFField;
        
        private string xMLField;
        
        private int estatusField;
        
        private string msgEstatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public int Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string MsgEstatus {
            get {
                return this.msgEstatusField;
            }
            set {
                this.msgEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Carga_TXTDTECompletedEventHandler(object sender, Carga_TXTDTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Carga_TXTDTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Carga_TXTDTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcesarTXT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcesarTXT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Carga_TXTBoletaCompletedEventHandler(object sender, Carga_TXTBoletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Carga_TXTBoletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Carga_TXTBoletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcesarTXTBoleta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcesarTXTBoleta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Solicitar_FolioCompletedEventHandler(object sender, Solicitar_FolioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Solicitar_FolioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Solicitar_FolioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SolicitarFolio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SolicitarFolio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Carga_LibroCVCompletedEventHandler(object sender, Carga_LibroCVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Carga_LibroCVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Carga_LibroCVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcesarLCV Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcesarLCV)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Carga_LibroGuiaCompletedEventHandler(object sender, Carga_LibroGuiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Carga_LibroGuiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Carga_LibroGuiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcesarLGuia Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcesarLGuia)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Estado_DTECompletedEventHandler(object sender, Estado_DTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Estado_DTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Estado_DTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstadoDocto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstadoDocto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Confirmar_DoctoCompletedEventHandler(object sender, Confirmar_DoctoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Confirmar_DoctoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Confirmar_DoctoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstadoDocto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstadoDocto)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591